### ISSUE TITLE
Suggest adding `severity!` methods to change log level

### ISSUE THREAD

**Issue by ioquatix** [ruby/logger#11]
It's a little bit inconvenient to write `logger.level = Logger::DEBUG`. It also means that the API can't be entirely replaced without reusing the values for `logger.level` exactly as defined by `Logger`. It would be nice if we could have methods for changing log level, e.g. `logger.debug!` which changes the log level to `Logger::DEBUG` and so on for other log levels.

**Comment by sonots** [comment]
this is added via https://github.com/ruby/logger/pull/15
