### ISSUE TITLE
Pre-set formatter message inconsistency at UNKNOWN level

### ISSUE THREAD

**Issue by luke-hill** [ruby/logger#13]
When using the formatter and the logger at a UNKNOWN level, the pre-set message string that is passed through to the proc is `ANY` instead of `UNKNOWN`

For all other logging levels the message is correct.

Couldn't find where this was generated in the source code, but advise either changing the message pre-set (Patch tweak), or altering the severity level (Major tweak)

EDIT: https://github.com/ruby/logger/blob/master/test/logger/test_logger.rb#L287 - This appears to be an error in the tests here, which looks like it's expecting the string "ANY"

**Comment by sonots** [comment]
ANY is coming from https://github.com/ruby/logger/blob/7651447953ceb1f92e548932730d4fba7ada70d0/lib/logger.rb#L593, but I am conservative about this ruby standard library, and won't change this spec.

**Comment by luke-hill** [comment]
This is a long-standing bug in the library though: https://github.com/ruby/logger/blob/7651447953ceb1f92e548932730d4fba7ada70d0/lib/logger.rb#L470-L487

That shows that it's looking for a severity which does exist or default to UNKNOWN, but then later on it looks for one called ANY.

Should just patch it up as a minor bugfix, and be done with it.

**Comment by sonots** [comment]
I found that UNKNOWN was ANY in the old days, and that was the reason.
https://github.com/ruby/logger/commit/e4d4f72d168a9fb2f953291587fb3d186f97d2b1

So, it is a bug. Hmm...
This behavior lasted 16 years. I can't say this is a minor bugfix. Hmm...

**Comment by sonots** [comment]
Decided. Let's fix it.

**Comment by sonots** [comment]
No, I was wrong. It was intended.

**Comment by sonots** [comment]
It looks that it was intended for making the label ANY for UNKNOWN.
https://github.com/ruby/logger/commit/525b58d97eb7dd1375f59dec6e4f34ebff0c0ecb
https://github.com/ruby/logger/commit/e4d4f72d168a9fb2f953291587fb3d186f97d2b1

I will ask to @nahi about the background.

**Comment by sonots** [comment]
As a spec, LABEL must be max 5 chars https://github.com/ruby/logger/blob/7651447953ceb1f92e548932730d4fba7ada70d0/lib/logger.rb#L589.
We can not make UNKNOWN label.

**Comment by luke-hill** [comment]
Hang on, this is still a defect though... 

If the limit is 5 characters for a msg dump, then the verbosity labels need changing so that Level 5 is ANY not UNKNOWN.

I appreciate this is a long-standing library in Ruby, but that doesn't mean it doesn't have any inherent defects.
