### ISSUE TITLE
[PLAN] Use test-unit and power-assert gem

### ISSUE THREAD

**Issue by sonots** [ruby/logger#27]
instead of built-in custom test library https://github.com/ruby/logger/tree/master/test/lib.

**Comment by hsbt** [comment]
+1

The current test suite of logger uses `assert_separately` provided by the custom test-unit on ruby core repository. 

https://github.com/ruby/logger/blob/master/test/logger/test_logdevice.rb#L608

We should replace it or make its assertion independent.

**Comment by sonots** [comment]
fixed cia #32
