### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by cup** [ruby/logger#31]
I can create this file:

~~~rb
require 'logger'
z = Logger.new STDOUT
z.info 'abcde'
z.warn 'abcde'
z.error 'abcde'
~~~

but it outputs in black and white. Is color an option?

**Comment by ioquatix** [comment]
By default? No.

There are a couple of options:

- Use a custom formatter with xterm colours.
- Use a different logger gem, e.g. https://github.com/socketry/console supports tty formatting out of the box.

**Comment by ioquatix** [comment]
I don't know if this is an option: https://rubygems.org/gems/logger-colors/versions/1.0.0 - it's very old. I've not tested it.

**Comment by cup** [comment]
@ioquatix I think I will use this one for now:

~~~rb
require 'ougai'
z = Ougai::Logger.new STDOUT
z.formatter = Ougai::Formatters::Readable.new
z.info 'abcde'
z.warn 'abcde'
z.error 'abcde'
~~~
