### ISSUE TITLE
1.4.0 release on Rubygems is missing files

### ISSUE THREAD

**Issue by da2x** [ruby/logger#38]
The `lib/logger/` directory is missing in the [1.4.0 rubygems release](https://rubygems.org/gems/logger/versions/1.4.0). It’s present in the [1.4.0 GitHub release](https://github.com/ruby/logger/releases/tag/v1.4.0).

    Traceback (most recent call last):
            9: from /rubygems/bin/nanoc:23:in `<main>'
            8: from /rubygems/bin/nanoc:23:in `load'
            7: from /rubygems/gems/nanoc-4.11.9/bin/nanoc:4:in `<top (required)>'
            6: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
            5: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
            4: from /rubygems/gems/nanoc-4.11.9/lib/nanoc.rb:42:in `<top (required)>'
            3: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
            2: from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
            1: from /rubygems/gems/logger-1.4.0/lib/logger.rb:15:in `<top (required)>'
    /rubygems/gems/logger-1.4.0/lib/logger.rb:15:in `require_relative': cannot load such file -- /rubygems/gems/logger-1.4.0/lib/logger/version (LoadError)

**Comment by sonots** [comment]
Oops, sorry.
1.4.1 has been released.
