### ISSUE TITLE
Does not accept `:daily` as shift_age

### ISSUE THREAD

**Issue by doloopwhile** [ruby/logger#46]
`Logger.new` fails if `shift_age` is a symbol.

Error:
```
irb(main):003:0> Logger.new('a.log', :daily)
ArgumentError (invalid :shift_age :daily, should be daily, weekly, monthly, or everytime)
```

Environment:
```
$ bundle list
Gems included by the bundle:
  * bundler (2.0.2)
  * logger (1.4.2)
```

Expected behavior (My suggestion for design change):

`Logger.new('a.log', :daily)` works as well as `Logger.new('a.log', 'daily')`.

**Comment by skryukov** [comment]
@sonots seems like a developer-friendly addition. What are your thoughts on this?

**Comment by hsbt** [comment]
Fixed at https://github.com/ruby/logger/commit/83502c2107c282e9e072865ab55252f2b37ec779
