### ISSUE TITLE
Per-thread log level?

### ISSUE THREAD

**Issue by mperham** [ruby/logger#84]
Hi, Sidekiq allows users to enable logging per-job so you can do this:

```ruby
SomeJob.set(log_level: :debug).perform_async(123)
```

This requires a thread-local log level. I have a ::Logger monkeypatch to enable this feature. Would you like me to create a PR to upstream it? This would allow the user to do something like:

```ruby
log = ::Logger.new(STDOUT, level: Logger::INFO)
log.debug("Not logged")

Thread.new do
  log.at_level(Logger::DEBUG) do
    log.debug("Logged")
  end
end.join

log.debug("Not logged")
```

https://github.com/mperham/sidekiq/blob/c12c8b567fcf3357bbd8b82a7d8651ddd7cc30a3/lib/sidekiq/logger.rb#L25-L73

**Comment by ioquatix** [comment]
Doing this per-thread will affect all fibers running on that thread which may be undesirable.

I'd suggest using the new `Fiber[:logger_level]` feature which has the correct scope (and is inherited to child fibers/threads).

Hypothetical implementation (Ruby 3.2+).

```ruby
def level
  Fiber[:logger_level] || @level
end

def at_level(level)
  old_level = Fiber[:logger_level]
  Fiber[:logger_level] = level
  yield
ensure
  Fiber[:logger_level] = old_level
end
```

For older rubies, using `Thread.current[:logger_level]` is probably okay.

**Comment by mperham** [comment]
I thought thread locals are also fiber local also, no?

**Comment by mperham** [comment]
Since this gem needs to support earlier Rubies, I'm ok with your implementation but `s/Fiber/Thread.current/g`

**Comment by ioquatix** [comment]
On Ruby 3.2+ we should definitely use inherited fiber variables as this actually nests into concurrency correctly.

**Comment by mperham** [comment]
That's fine. I'm not going to work on a PR until a committer shows interest.

**Comment by ioquatix** [comment]
I'm a Ruby core committer, but not the maintainer of logger. I'm showing interest.

**Comment by mperham** [comment]
I mean a committer of this repo. Someone who can merge PRs.

**Comment by ioquatix** [comment]
I can merge PRs on this repo.

**Comment by mperham** [comment]
@ioquatix Were you interested in pulling this in so we can simplify Sidekiq's logger?
